apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret.yaml
  - configmap.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: protostar-fastapi
        namespace: service
        labels:
          env: dev
      spec:
        template:
          metadata:
            labels:
              env: dev